# Welcome to Jekyll!
#

# Site settings
title: NaSTA Vision
description: |
  Showcase your University's best musical talent
owner: LA1:TV # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: nastavision@la1tv.co.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nastavision.tv" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/la1tv
  github: https://github.com/la1tv
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
